### ISSUE TITLE
how to get rid of the dialogue box which pops up when server runs...how can we remove it?

### ISSUE THREAD

**Issue by MansiGoyal06** [ckeditor/ckeditor5-collaboration-samples#18]
![Screenshot (4)](https://user-images.githubusercontent.com/55283848/81405124-adf4bf80-9154-11ea-8e6f-9ae3d7e8c3e4.png)

**Comment by Mgsy** [comment]
Hi, the dialog is created by `createDialog()` function in the sample file - https://github.com/ckeditor/ckeditor5-collaboration-samples/blob/master/classic-editor-with-real-time-collaboration/samples/classic-editor-with-real-time-collaboration.html#L200. 

Just remove it and pass your Cloud Services credentials directly to the `cloudServices` object, for example:

```javascript
watchdog.create( document.querySelector( '.editor' ), {
	initialData,
	cloudServices: {
		tokenUrl: 'your-token-url',
		uploadUrl: 'your-upload-url',
		webSocketUrl: 'your-ws-url'
	},
	collaboration: {
		channelId: 'your-channel-id'
	},
	sidebar: {
		container: document.querySelector( '.sidebar' )
	},
	presenceList: {
		container: document.querySelector( '.presence' )
	}
} );
```

**Comment by parth-gr** [comment]
Thanks for your reply, I am going from the same problem.
After making the code hardcoded then also the dialog is asking for the details.

And also after entering the Token URL its ask for to choose the user so how to get rid of this.
And make a fully automatic device, which directly serves the Editor.(I am even not interested in users so better if I can remove this property).
