### ISSUE TITLE
Want to get rid of Dialog Box , I want to make a automated program that directly opens the Editor.

### ISSUE THREAD

**Issue by parth-gr** [ckeditor/ckeditor5-collaboration-samples#19]
![81405124-adf4bf80-9154-11ea-8e6f-9ae3d7e8c3e4](https://user-images.githubusercontent.com/50455445/81466099-82bdaf00-91ec-11ea-93fc-89a21f8ac664.png)

Previously posted by you to hardcode the classic-editor-with-real-time-collaboration.html, but it doesn't work 
and you only suggested for the URL's but if write tokens then a drop-down comes to select the names of the user, and I don't want the list to come and directly wants an automated software that works on different channels.
If I will be purchasing the token then the dialogue will be removed or then also I have to hardcode for that.

**Comment by parth-gr** [comment]
Sir any response.

**Comment by Mgsy** [comment]
Hi @parth-gr, I'm sorry for the late response. The dialog box is our custom implementation for the sample that should allow a user to set up the whole environment more quickly. If you'd like to remove it, you should modify the code responsible for displaying it.
