### ISSUE TITLE
How to get the data of Ckeditor-5

### ISSUE THREAD

**Issue by parth-gr** [ckeditor/ckeditor5-collaboration-samples#20]
I want to retrieve data from the CKEditor-5 to save it to my local database, so how to fetch the data from it. And also there is an inbuilt functionality that helps me to apply to debounce time to store data in the database. 
I am working on real-time-collaboration-for-angular.

**Comment by Mgsy** [comment]
Hi, you can get the data from the editor by calling `editor.getData()`.

For more information, see our [Getting and saving data guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html).

**Comment by parth-gr** [comment]
Where to call the function getData(), in which module.
Can you specify the location where we can create the instance and call this function?

**Comment by Mgsy** [comment]
See our documentation about [accessing the editor instance in Angular integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#accessing-the-editor-instance).
