### ISSUE TITLE
Unable to integrate angular 5

### ISSUE THREAD

**Issue by arulmb01361** [ckeditor/ckeditor5-collaboration-samples#23]
ERROR in ./build/classic-editor-with-real-time-collaboration.js
Module parse failed: Unexpected token (43203:7)
You may need an appropriate loader to handle this file type.
|                                       t.model.change(t => {
|                                               for (const [e, n] of s) t.setAttributes({
|                                                       ...pm,
|                                                       ...n
|                                               }, e)

**Comment by arulmb01361** [comment]
ck editor build not supporting to integrate angular 5 version application.

**Comment by Mgsy** [comment]
Hi! CKEditor 5 supports Angular 5+, however, the package version that should be used depends on the Angular version:
> Versions 1.x.x – For Angular 5-8 applications. We no longer provide support for these as the official support for these Angular versions was dropped.
Versions 2.x.x – For Angular 9.1+ applications. These versions are currently actively supported.

For more information about integrating CKEditor 5 with real-time collaboration and Angular, see the [Angular integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html) and [our sample](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-angular).
