### ISSUE TITLE
ETA for track-changes-for-vuejs

### ISSUE THREAD

**Issue by CG-root** [ckeditor/ckeditor5-collaboration-samples#24]
Hi
Is there any ETA for track changes for vuejs?

**Comment by f1ames** [comment]
Hi @CG-root,
thanks for your patience. We have released brand new samples, which includes Vue with Track Changes feature. Please take a look on:
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-vue
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/collaboration-for-vue
