### ISSUE TITLE
Setup example for nextjs

### ISSUE THREAD

**Issue by viperfx** [ckeditor/ckeditor5-collaboration-samples#26]
Can we have a working example that uses NextJS and with recent React syntax? e.g. Without using class-based components if possible.

**Comment by f1ames** [comment]
Hi @viperfx,
thanks for your patience! We have brand new React (hook-based) and Next.js samples. Please take a look on:
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-react
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-next
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/collaboration-for-react
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/collaboration-for-next
