### ISSUE TITLE
Create additional asynchronous samples for Vue

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5-collaboration-samples#27]
Currently, we only offer samples for Angular and React that showcase how to integrate the asynchronous Track changes and Revision history with these frameworks.

Similar samples for Vue could also be prapared.

**Comment by f1ames** [comment]
With the current release of updated collaboration samples, we have brand new RTC and non-RTC Vue samples:
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-vue
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/collaboration-for-vue
