### ISSUE TITLE
Import from Word

### ISSUE THREAD

**Issue by JTGiLard** [ckeditor/ckeditor5-collaboration-samples#29]
Hi, I am new to CKEditor 5, I tried out the collaboration-track changes html samples. I want to add the Import from Word feature and track changes in a html sample to show my users. Are there any samples or detail steps to make this happen? Thanks!

**Comment by f1ames** [comment]
Hi @JTGiLard,
please refer to [real-time-collaboration-editor-classic](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-editor-classic) and [collaboration-editor-classic](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/collaboration-editor-classic) - both have Import from Word and Track Changes features enabled.
