### ISSUE TITLE
Can't build real-time-collaboration-revision-history-for-react

### ISSUE THREAD

**Issue by DeltekDavid** [ckeditor/ckeditor5-collaboration-samples#31]
Tried building `build real-time-collaboration-revision-history-for-react` using `npm install` per the README, but got:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: real-time-collaboration-revision-history-for-react@0.1.0
npm ERR! Found: webpack@5.91.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.73.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from uglifyjs-webpack-plugin@2.2.0
npm ERR! node_modules/uglifyjs-webpack-plugin
npm ERR!   dev uglifyjs-webpack-plugin@"^2.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\myusername\AppData\Local\npm-cache\_logs\2024-04-22T18_26_10_640Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\myusername\AppData\Local\npm-cache\_logs\2024-04-22T18_26_10_640Z-debug-0.log
```

**Comment by f1ames** [comment]
Hi @DeltekDavid,
we have recently published updated samples, so you may want to try running it again. The sample you mentioned was moved as [`real-time-collaboration-for-react`](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-react). Please refer to its' README on how to run it (but in short, it's just `yarn && yarn dev/build`).

**Comment by DeltekDavid** [comment]
Nice, so much cleaner! We will refer to this sample when we return to collaborative editing. 

Hope there are plans to have TypeScript examples (if not the default, then at least alongside vanilla JS. We are a TypeScript shop). Thanks!
